const { gql } = require("apollo-server");

module.exports = gql`

  ############################################################ ProjectUSSCQ
  type Activite {
    id: ID!
    name: String!
    resource: ID!
    date: String!
    sujet: String!
    remarques: String! 
    recommendation: String                                                                                                                       
  }
  type Response {
    id: ID!
    name: String!
    resource: ID!
    degre: String!
    description: String!
    dateLimite: String!
    etat: String!
  }
  scalar Upload
  # To Create A Ressource
  type Resource {
    id: ID!
    pdfFile: Upload!
    ref: String!
    source: String!
    date: String!
    description: String!
    tache: String!
  }
  # To Query a Ressource
  type ResourceDetails {
    id: ID!
    pdfFile: String!
    ref: String!
    source: String!
    date: String!
    description: String!
    tache: String!
  }

  input AdminInput {
    firstname: String!
    name: String!
    grade: String!
  }
  input ModifyProjectInput {
    id: ID!
    name: String!
    admin: [AdminInput]
    createdAt: String
    updatedAt: String
    source: String!
    benificaire: [String]!
    periodeProject: [String]!
    integration: [String]!
    encryptionType: [String]!
    lengthKey: [String]!
    liaison: [String]!
    KeyDuration: Int!
    description: String!
    partage: String!
  }
  input CreateActiviteInput {
    projectId: ID!
    resourceRef: String!
    date: String!
    sujet: String!
    remarques: String!
    recommendation: String
  }
  input CreateResponseInput {
    projectId: ID!
    resourceRef: String!
    degre: String!
    description: String!
    dateLimite: String!
  }
  input CreateResourceInput {
    projectId: ID!
    pdfFile: Upload!
    ref: String!
    source: String!
    date: String!
    description: String!
    tache: String!
  }

  input ModifyActiviteInput {
    projectId: ID!
    activityId: ID!
    name: String!
    date: String!
    sujet: String!
    remarques: String!
    recommendation: String

  }
  input ModifyResponseInput{
    projectId: ID!
    responseId: ID!
    degre: String!
    description: String!
    dateLimite: String!
    etat: String!
  }
  input ModifyRessourceInput {
    projectId: ID!
    ressourceId: ID!
    # pdfFile: String!
    ref: String!
    source: String!
    date: String!
    description: String!
    # tache: String!
  }
  type ProjetUSSCQ {
    id: ID!
    name: String!
    admin: [User!]!
    source: String!
    benificaire: [String]!
    periodeProject: [String]!
    integration: [String]!
    encryptionType: [String]!
    lengthKey: [String]!
    liaison: [String]!
    KeyDuration: Int!
    activite: [Activite!]!
    response: [Response!]!
    resource: [ResourceDetails]!
    description: String!
    partage: String!
    createdAt: String!
    updatedAt: String!
  }



  ############################################################ ProjectLABO

  input ObjectInput {
    label: String!
    value: String!
  }
  input ObjectLivrableInput {
    label: String!
    value: String!
    checked: Boolean!
  }
#  input FormateurInput {
#     firstname: String!
#     name: String!
#     grade: String!
#   }
input ModifyProjectLaboInput {
    id: ID!
    nameProject: String!
    adminProject: [AdminInput]
    referenceTypeProject: [ObjectInput]!
    livrablesProject: [ObjectLivrableInput]!
    encryptionTypeProject: [ObjectInput]!
    integrationProject: [ObjectInput]!
    descriptionProject: String!
    partageProject: String!
    # versionProject: [Version]!
    # reseauProject: [Reseau]!
    # missionProject: [Mission!]!
    # statusProject: String!
    formateurProject: [String]!
    # createdAt: String!
    updatedAt: String!
}
  input CreateVersionInput {
    projectId: ID!
    nameVersion: String!
    descriptionVersion: String!
  }
  type Version {
    id: ID!
    versionId: String!
    nameVersion: String!
    descriptionVersion: String!
  }
  type Reseau {
    id: ID!
    namereseau: String!
    # projetreseau: [ProjectLabo!]!
    versionreseau: String!
    typereseau: String!
    referencereseau: String!
    livrablereseau: String!
    durationmission: String!
    benificiairereseau: String!
  }
  type Mission {
    id: ID!
    namemission: String!
    # projetmission: [ProjectLabo!]!
    versionmission: String!
    destination: String!
    referencemission: String!
    formateur: [User!]!
    typeuser: String!
  }
  type Object {
    label: String!
    value: String!
  }
  type ObjectLivrable {
    label: String!
    value: String!
    checked: Boolean!
  }
  type ProjectLabo {
    id: ID!
    nameProject: String!
    adminProject: [User!]!
    referenceTypeProject: [Object]!
    livrablesProject: [ObjectLivrable]!
    encryptionTypeProject: [Object]!
    integrationProject: [Object]!
    descriptionProject: String!
    partageProject: String!
    versionProject: [Version]!
    reseauProject: [Reseau]!
    missionProject: [Mission!]!
    statusProject: String!
    formateurProject: [String]!
    createdAt: String!
    updatedAt: String!
  }
  type User {
    id: ID!
    firstname: String!
    name: String!
    login: String!
    direction: String!
    grade: String!
    password: String!
    firstConnect: String!
    userType: [String]!
    projectLabo: [ProjectLabo]
    projectQt: [ProjetUSSCQ]
  }
  type ResourceCreationResult {
    success: Boolean!
    message: String
    resourceRef: String
  }

  ############################################################################ Mutation
  type Mutation {
       # # #    # # #    # # #    # # #    # # #    # # #  ProjectUSSCQ
    # Modify ProjectUSSCQ
    modifyProject(input: ModifyProjectInput!): ProjetUSSCQ!

     # Create Ressource Project USSCQ
    createResource(input: CreateResourceInput!): ResourceCreationResult
     #  Modify Ressource Project USSCQ
    modifyRessource(input: ModifyRessourceInput!): ResourceDetails!
    # Delete Ressource Project USSCQ
    deleteRessource(projectId: ID!, ressourceId: ID!): ResourceDetails!

    # Create Activity Project USSCQ ( Reunion )
    createActivite(input: CreateActiviteInput!): Activite!
    # Modify Activity Project USSCQ
    modifyActivite(input: ModifyActiviteInput!): Activite!
    # Delete Activity Project USSCQ
    deleteActivite(projectId: ID!, activiteId: ID!): Activite!
   
    # Create Activity ( Response ) Project USSCQ 
    createResponse(input: CreateResponseInput!): Response!
    # Modify Activity ( Response ) Project USSCQ
    modifyResponse(input: ModifyResponseInput!): Response!
    # Delete Activity ( Response ) Project USSCQ
    deleteResponse(projectId: ID!, responseId: ID!): Response!

    # # #    # # #    # # #    # # #    # # #    # # #  ProjectLABO
    # Create Version Project LABO
    createVersion(input: CreateVersionInput!): Version!
    # Modify Project LABO
    modifyProjectLabo(input: ModifyProjectLaboInput!): ProjectLabo!
  }

  ############################################################################ Query
  type Query {
    getProjects: [ProjetUSSCQ]
    project(id: ID!): ProjetUSSCQ

    getActivities(projectId: ID!): [Activite]
    getActivity(projectId: ID!, activityId: ID!): Activite

    getProjectsLabo: [ProjectLabo]
    projectLabo(id: ID!): ProjectLabo

    getVersions(projectId: ID!): [Version]
    getVersion(projectId: ID!, versionID: ID!): Version
  }
`;
