////////////Creer un projet/////////////////

export const PROJECT_LABO_CREATE_REQUEST = "PROJECT_LABO_CREATE_REQUEST";
export const PROJECT_LABO_CREATE_SUCCESS = "PROJECT_LABO_CREATE_SUCCESS";
export const PROJECT_LABO_CREATE_FAIL = "PROJECT_LABO_CREATE_FAIL";
