////////////Creer un projet/////////////////

export const PROJECT_USSQ_CREATE_REQUEST = "PROJECT_USSQ_CREATE_REQUEST";
export const PROJECT_USSQ_CREATE_SUCCESS = "PROJECT_USSQ_CREATE_SUCCESS";
export const PROJECT_USSQ_CREATE_FAIL = "PROJECT_USSQ_CREATE_FAIL";
